type: base
build:
  auto_version: true
  architectures:
    - amd64
    - arm64
  variants:
    - tag: "15"
      args:
        PKG_BRANCH: quarterly
      aliases: ["latest", "15-quarterly"]
    - tag: "15-latest"
      args:
        PKG_BRANCH: latest
